kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: usr-workshop
  namespace: workshop-demo
  uid: 00800c73-1429-47b8-9c11-ec4657d8140e
  resourceVersion: '38554'
  creationTimestamp: '2023-10-24T16:59:50Z'
  labels:
    app: usr-workshop
    app.kubernetes.io/component: usr-workshop
    app.kubernetes.io/instance: usr-workshop
  annotations:
    openshift.io/host.generated: 'true'
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: route.openshift.io/v1
      time: '2023-10-24T16:59:50Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
        'f:spec':
          'f:port':
            .: {}
            'f:targetPort': {}
          'f:to':
            'f:kind': {}
            'f:name': {}
            'f:weight': {}
          'f:wildcardPolicy': {}
    - manager: openshift-router
      operation: Update
      apiVersion: route.openshift.io/v1
      time: '2023-10-24T16:59:50Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:ingress': {}
      subresource: status
spec:
  host: usr-workshop-workshop-demo.apps-crc.testing
  to:
    kind: Service
    name: usr-workshop
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None
status:
  ingress:
    - host: usr-workshop-workshop-demo.apps-crc.testing
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2023-10-24T16:59:50Z'
      wildcardPolicy: None
      routerCanonicalHostname: router-default.apps-crc.testing
