kind: Service
apiVersion: v1
metadata:
  name: usr-workshop
  namespace: workshop-demo
  labels:
    app: usr-workshop
    app.kubernetes.io/component: usr-workshop
    app.kubernetes.io/instance: usr-workshop
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
